# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Izrael', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izraeldataforpacking',
            name='post_number',
            field=models.CharField(max_length=30),
        ),
    ]
