# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-18 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170918_1537'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviews',
            table='\u041e\u0442\u0437\u044b\u0432\u044b \u043a\u043b\u0438\u0435\u043d\u0442\u043e\u0432',
        ),
    ]
