# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170918_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviews_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Customer'),
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='Reviews',
        ),
    ]
