# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-02 13:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0006_auto_20171104_1755'),
        ('login', '0009_calculatorgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNovaPoshta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('address_client', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10)])),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='LossInAir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_loss', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price_our', models.FloatField(blank=True, null=True)),
                ('price_client', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(max_length=150)),
                ('date_shortages', models.DateTimeField(auto_now_add=True)),
                ('air', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Air')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Customer')),
                ('name_tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.PackProduct')),
                ('plomba_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.PlombaDimension')),
            ],
        ),
        migrations.CreateModel(
            name='PackCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('model_number', models.CharField(blank=True, max_length=200, null=True)),
                ('url1', models.CharField(blank=True, max_length=250, null=True)),
                ('url2', models.CharField(blank=True, max_length=250, null=True)),
                ('word_search', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(blank=True, max_length=250, null=True)),
                ('company_transporter', models.CharField(blank=True, max_length=250, null=True)),
                ('recipient_our', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_recip', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='file_document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='file_document',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='file_document',
            table=None,
        ),
    ]
