# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20180602_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_add', models.DateField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
