# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customernovaposhta',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='packcustomer',
            name='customer',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/blog/'),
        ),
        migrations.DeleteModel(
            name='CustomerNovaPoshta',
        ),
        migrations.DeleteModel(
            name='PackCustomer',
        ),
    ]
