# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-18 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LK', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('post_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('treck', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LK.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('gander', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6)),
                ('skype', models.CharField(max_length=30)),
                ('stavka', models.FloatField(default=7)),
                ('code_clienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
