# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code_clienta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LK.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stavka',
            field=models.IntegerField(default=1),
        ),
    ]
