# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-18 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_reviews'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviews',
            table='Reviews',
        ),
    ]
