# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170807_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stavka',
            field=models.FloatField(default=1),
        ),
    ]
