# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0001_initial'),
        ('login', '0003_auto_20170813_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('post_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('treck', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Customer')),
            ],
        ),
    ]
