# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170918_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='text_reviews',
            field=models.TextField(max_length=250, verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043e\u0442\u0437\u044b\u0432'),
        ),
    ]
