# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-02 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_expectedcargo_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedcargo',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LK.Customer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stavka',
            field=models.FloatField(default=7),
        ),
    ]
