# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-04 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20171019_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectedcargo',
            name='customer',
        ),
        migrations.DeleteModel(
            name='ExpectedCargo',
        ),
    ]
