# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0006_auto_20171104_1755'),
        ('login', '0007_auto_20171104_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=b'')),
                ('packid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Pack')),
            ],
            options={
                'db_table': 'File',
            },
        ),
    ]
