# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_calculatorgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_document',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
