# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-01 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20180301_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_document',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
