# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_lossinair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossinair',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lossinair',
            name='name_tovar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lossinair',
            name='plomba_number',
            field=models.IntegerField(),
        ),
    ]
