# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0006_auto_20171104_1755'),
        ('login', '0016_customernovaposhta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('model_number', models.CharField(blank=True, max_length=200, null=True)),
                ('url1', models.CharField(blank=True, max_length=250, null=True)),
                ('url2', models.CharField(blank=True, max_length=250, null=True)),
                ('word_search', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Customer')),
            ],
        ),
    ]
