# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_packcustomer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='packcustomer',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
