# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_packcustomer_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packcustomer',
            old_name='company',
            new_name='company_transporter',
        ),
        migrations.AddField(
            model_name='packcustomer',
            name='phone_recip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='packcustomer',
            name='recipient_our',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
