# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20180311_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_document',
            name='name',
            field=models.IntegerField(),
        ),
    ]
