# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/blog/'),
        ),
    ]
