# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-19 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_auto_20190314_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdatauploadfrom1c',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airdatauploadfrom1c',
            name='difference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='airdatauploadfrom1c',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LK.Customer'),
        ),
        # migrations.AlterField(
        #     model_name='buyout',
        #     name='amount_shipping',
        #     field=models.FloatField(blank=True, null=True, verbose_name='\u0441\u0443\u043c\u043c\u0430 \u0437\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0443'),
        # ),
        # migrations.AlterField(
        #     model_name='buyout',
        #     name='sum_buyout',
        #     field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='\u0441\u0443\u043c\u043c\u0430 \u0432\u044b\u043a\u0443\u043f\u0430'),
        # ),
    ]
