# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-04 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0002_auto_20171104_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'managed': False},
        ),
    ]
